eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          username: 763119781@qq.com
          password: zxcv1234
          uri: https://gitee.com/xiaoliuyang/test
server:
  port: 9100